# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWFObi7e4T1HjCH57adp814JBzK8njdF
"""

import json
from pathlib import Path

import torch
from PIL import Image
from pycocotools.coco import COCO
from torch.utils.data import DataLoader, Dataset
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from torchvision.models.detection import fasterrcnn_mobilenet_v3_large_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.transforms import v2 as T

# ================= DATASET =================
class COCODetectionDataset(Dataset):
    def __init__(self, images_dir, annotation_file, cat_id_to_label, transforms=None):
        self.images_dir = Path(images_dir)
        self.coco = COCO(str(annotation_file))
        self.image_ids = list(self.coco.imgs.keys())
        self.cat_id_to_label = cat_id_to_label
        self.transforms = transforms

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        image_id = self.image_ids[idx]
        image_info = self.coco.loadImgs([image_id])[0]
        image_path = self.images_dir / image_info["file_name"]
        image = Image.open(image_path).convert("RGB")

        ann_ids = self.coco.getAnnIds(imgIds=[image_id])
        anns = self.coco.loadAnns(ann_ids)

        boxes, labels = [], []

        for ann in anns:
            x, y, w, h = ann["bbox"]
            if w > 0 and h > 0:
                boxes.append([x, y, x + w, y + h])
                labels.append(self.cat_id_to_label[ann["category_id"]])

        boxes = torch.tensor(boxes, dtype=torch.float32) if boxes else torch.zeros((0, 4))
        labels = torch.tensor(labels, dtype=torch.int64) if labels else torch.zeros((0,), dtype=torch.int64)

        target = {
            "boxes": boxes,
            "labels": labels,
            "image_id": torch.tensor([image_id]),
        }

        if self.transforms:
            image = self.transforms(image)

        return image, target


def collate_fn(batch):
    return tuple(zip(*batch))


# ================= MODEL =================
def build_model(num_classes):
    model = fasterrcnn_mobilenet_v3_large_fpn(weights="DEFAULT")
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    return model


# ================= EVAL =================
def evaluate_map(model, data_loader, device):
    model.eval()
    metric = MeanAveragePrecision()

    with torch.no_grad():
        for images, targets in data_loader:
            images = [img.to(device) for img in images]
            outputs = model(images)

            preds = []
            gts = []

            for o, t in zip(outputs, targets):
                preds.append({
                    "boxes": o["boxes"].cpu(),
                    "scores": o["scores"].cpu(),
                    "labels": o["labels"].cpu(),
                })
                gts.append({
                    "boxes": t["boxes"],
                    "labels": t["labels"],
                })

            metric.update(preds, gts)

    return metric.compute()


# ================= TRAIN =================
def train_one_epoch(model, optimizer, loader, device, scaler):
    model.train()
    total_loss = 0

    for images, targets in loader:
        images = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        with torch.cuda.amp.autocast():
            loss_dict = model(images, targets)
            loss = sum(loss_dict.values())

        optimizer.zero_grad()
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

    return total_loss / len(loader)


# ================= MAIN =================
def main():
    # ===== CONFIG =====
    dataset_root = Path("TODO") # thay bang duong dan den tap du lieu sau xu ly
    output_dir = Path("TODO") # thay bang duong dan den thu muc luu model sau khi train
    output_dir.mkdir(exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Using:", device)

    # ===== LOAD CLASS =====
    with open(dataset_root / "train/_annotations.coco.json") as f:
        train_json = json.load(f)

    categories = sorted(train_json["categories"], key=lambda x: x["id"])
    cat_id_to_label = {c["id"]: i + 1 for i, c in enumerate(categories)}

    # ===== TRANSFORM =====
    transform = T.Compose([
        T.ToImage(),
        T.ToDtype(torch.float32, scale=True),
    ])

    # ===== DATASET =====
    train_ds = COCODetectionDataset(dataset_root/"train", dataset_root/"train/_annotations.coco.json", cat_id_to_label, transform)
    val_ds   = COCODetectionDataset(dataset_root/"valid", dataset_root/"valid/_annotations.coco.json", cat_id_to_label, transform)

    train_loader = DataLoader(
        train_ds, batch_size=4, shuffle=True,
        num_workers=2, pin_memory=True, collate_fn=collate_fn
    )

    val_loader = DataLoader(
        val_ds, batch_size=4, shuffle=False,
        num_workers=2, pin_memory=True, collate_fn=collate_fn
    )

    # ===== MODEL =====
    model = build_model(len(categories) + 1).to(device)

    optimizer = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9)

    scaler = torch.cuda.amp.GradScaler()  # 🔥 tăng tốc

    best_map = 0

    # ===== TRAIN LOOP =====
    for epoch in range(50):
        loss = train_one_epoch(model, optimizer, train_loader, device, scaler)
        metrics = evaluate_map(model, val_loader, device)

        print(f"Epoch {epoch+1} | Loss {loss:.4f} | mAP {metrics['map']:.4f}")

        if metrics["map"] > best_map:
            best_map = metrics["map"]
            torch.save(model.state_dict(), output_dir/"best.pth")

    print("BEST mAP:", best_map)


# ===== RUN =====
main()